server:
  port: 7001
spring:
  application:
    name: eureka-client-7001
eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.46:8761/eureka/,http://192.168.10.46:8762/eureka/,http://192.168.10.46:8763/eureka/
